### ISSUE TITLE
Create a Recipe Page

### ISSUE THREAD

**Issue by anthonynikhilreddy** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-1#7]

**Comment by BhanuPrakashNani** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-1/7?planning-poker) with Zenhub @BhanuPrakashNani @abijith-pradeep @anthonynikhilreddy @Naveen-an4207 @Caulhong
