### ISSUE TITLE
testing party bug: checkout button doesn't update cart & cart is not clickable 

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-1#96]
for example: 
- clicked on "buttermilk pound cake" 
- clicked "add to cart" under ingredients
- clicked "checkout" 
The cart in the top right corner briefly flashed to 10 and then back to zero. The "view cart" button disappeared and went back to "add to cart"

**Comment by anthonynikhilreddy** [comment]
hey Malu, great observation 

the checkout button directly places the order, we have to put a toast/alert for the user in the UI saying the order has been placed successfully. 

you can check if the order has been placed in the profile page.

but great observation. we will add that toast.

**Comment by maludee** [comment]
oh thank you for the follow up! I didn't see the toast alert, but confirming I do see all of my pending orders in my profile
